required-players: 2
maximum-players: 20
countdown-time: 10
lobby-spawn:
    world: world
    x: 0.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
arenas:
  0:
    line-corner-1:
      world: world
      x: 0.5
      y: 64.0
      z: 0.5
    line-corner-2:
      world: world
      x: 0.5
      y: 64.0
      z: 0.5
    red-spawn:
      world: world
      x: 0.5
      y: 64.0
      z: 0.5
      yaw: 0.0
      pitch: 0.0
    blue-spawn:
        world: world
        x: 0.5
        y: 64.0
        z: 0.5
        yaw: 0.0
        pitch: 0.0
  1:
    line-corner-1:
      world: world
      x: 0.5
      y: 64.0
      z: 0.5
    line-corner-2:
      world: world
      x: 0.5
      y: 64.0
      z: 0.5
    red-spawn:
      world: world
      x: 0.5
      y: 64.0
      z: 0.5
      yaw: 0.0
      pitch: 0.0
    blue-spawn:
      world: world
      x: 0.5
      y: 64.0
      z: 0.5
      yaw: 0.0
      pitch: 0.0